version: '3'

services:
  api:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - .:/coffee_passport
      - public-data:/coffee_passport/public
      - tmp-data:/coffee_passport/tmp
      - log-data:/coffee_passport/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/coffee_passport/public
      - tmp-data:/coffee_passport/tmp
    ports:
      - 80:80
    depends_on:
      - api
  front:
    build: ./front
    volumes:
      - ./front:/coffee_passport
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: